In [1]:
import numpy as np
import sympy as sp

<img src="img/00_elastic.png" width="500"/>

### Формулы и термины:

R - выручка

C - затраты(издержки)

E_d - ?

E_r - ?

In [163]:
# Дано
p, x = sp.symbols('p, x')
C = 40 + x  # расходы C(x)
f = sp.Eq(3 * p + sp.sqrt(x), 50)  # уравнение Спроса
C, f

(x + 40, Eq(3*p + sqrt(x), 50))

In [164]:
R = p * x  # Выручка
R

p*x

In [165]:
x_val = sp.solve(f, x)[0]  # функция Спроса D(p)
x_val

(3*p - 50)**2

In [166]:
R = R.subs({x: x_val}) # замена x на значение
R

p*(3*p - 50)**2

In [167]:
R_diff = R.diff()  # максимум прибыли 
# производная по p
R_diff

p*(18*p - 300) + (3*p - 50)**2

In [168]:
# Решаем уравнение при # p=10
TR_diff_10 = R_diff.subs({p: 10})
TR_diff_10

-800

In [169]:
# эластичность Спроса
# E_d = D' * p / D
E_d = x_val.diff() * p / x_val
E_d = sp.simplify(E_d)
E_d

6*p/(3*p - 50)

In [170]:
# эластичность Выручки
# E_r = R' * p / R или E_r = 1 + E_d
E_r = 1 + E_d
E_r

6*p/(3*p - 50) + 1

In [171]:
# Прибыль
P = R - C
P

p*(3*p - 50)**2 - x - 40

In [172]:
P = P.subs({x: x_val})
P

p*(3*p - 50)**2 - (3*p - 50)**2 - 40

In [173]:
P_diff = P.diff()
P_diff

p*(18*p - 300) - 18*p + (3*p - 50)**2 + 300

In [174]:
p_val = sp.solve(sp.Eq(0, P_diff))[0]
p_val

56/9

In [175]:
# 1
print(f'x = {x_val}')
print(f'R\' = {R_diff}')
print(f"Предельная выручка в точке p=10: {TR_diff_10}")


x = (3*p - 50)**2
R' = p*(18*p - 300) + (3*p - 50)**2
Предельная выручка в точке p=10: -800


In [176]:
# 2
print(f'E_d = {E_d}')
print(f'E_d(10) = {E_d.subs({p: 10})}')

print(f'E_r={E_r}')
print(f'E_r(10)={E_r.subs({p: 10})}')


E_d = 6*p/(3*p - 50)
E_d(10) = -3
E_r=6*p/(3*p - 50) + 1
E_r(10)=-2


In [177]:
# 3

print(f'C(x) = {C}')
print(f'p = {p_val.round(2)}')
print(f'P_max = {P.subs({p: p_val}).round(2)}')
print(f'x = {x_val.subs({p: p_val}).round(2)}')


C(x) = x + 40
p=6.22
P_max = 5087.06
x = 981.78


<img src="img/t2.png" width="500"/>

In [178]:
x = sp.Symbol('x')
p_D = -2*x + 250
p_S = x + 100


In [179]:
# 1
sp.solve(sp.Eq(p_D, p_S), x)[0]

50

In [180]:
# 2
p_S_delta = p_S + 10
round(sp.solve(sp.Eq(p_D, p_S_delta), x)[0], 2)


46.67

In [181]:
# 3
p_D_delta = p_D + 5
round(sp.solve(sp.Eq(p_D_delta, p_S), x)[0], 2)

51.67

In [182]:
# 4
z = sp.Symbol('z')

res = sp.simplify(sp.Eq(p_D, p_S+z))
res

Eq(3*x + z, 150)

In [183]:
# x*z => max

In [184]:
x_val = sp.solve(sp.Eq((150*x-3*x**2).diff(), 0))[0]
print(f"x = {x_val}")

x = 25


<img src="img/t3.png" width="500"/>

### Инфа:
- Субсидия — выплаты, предоставляемые за счёт государственного или местного бюджета, а также выплаты из специальных фондов для юридических и физических лиц, местных органов власти, других государств.

In [185]:
x = sp.Symbol('x')
t = sp.Symbol('t') # налог
p_D = -x + 100
p_S = 3 * x + 20

In [186]:
# 1
sp.solve(sp.Eq(p_D, p_S), x)[0]

20

In [187]:
# 2
sp.solve(sp.Eq(p_D, p_S + t), t)[0].subs({x: 15})

20

In [188]:
# 3
s = 384 / x
x_val = max(sp.solve(sp.Eq(p_D, p_S - s), x)) #24
s.subs({x: x_val}) # субсидии

16

<img src="img/t4.png" width="500"/>

In [480]:
x1, x2 = sp.symbols('x_1, x_2')
p_1, p_2 = sp.symbols('p_1, p_2')

In [481]:
def express(a, b, name):
    # выразить одну через другую
    sym = sp.symbols(name)
    sol = sp.solve(a-sym, b)
    assert len(sol) == 1
    return (sym, sol[0])

In [482]:
x_1 = 70 - p_1
x_2 = 76 - 2*p_2


In [483]:
p1 = express(x_1, p_1, "x_1")[1]
p2 = express(x_2, p_2, "x_2")[1]
p1, p2

(70 - x_1, 38 - x_2/2)

In [484]:
C = (4 * x1 ** 2) + (5 * x1 * x2) + (x2 ** 2)
C

4*x_1**2 + 5*x_1*x_2 + x_2**2

In [485]:
R = p1*x1 + p2*x2
R

x_1*(70 - x_1) + x_2*(38 - x_2/2)

In [486]:
P = R - C # тоже какая-то формула
P

-4*x_1**2 - 5*x_1*x_2 + x_1*(70 - x_1) - x_2**2 + x_2*(38 - x_2/2)

In [494]:
res = sp.solve([sp.Eq(0, P.diff(x1)), sp.Eq(0, P.diff(x2))])
p_1_val = res[x1]
p_2_val = res[x2]
print(f'p_1 = {p_1_val}\np_2 = {p_2_val}')

p_1 = 4
p_2 = 6


In [488]:
E_d1 = x_1.diff() * p_1/x_1 # формула для эластичности
E_d2 = (x_2.diff() * p_2/x_2).simplify()


In [453]:
E_d1

-p_1/(70 - p_1)

In [454]:
E_d2

p_2/(p_2 - 38)

In [465]:
# вторая производная коэфф матрицы
coef1 = P.diff(x1).diff(x1) # глав диагональ
coef2 = P.diff(x2).diff(x2) # глав диагональ
coef3 = P.diff(x1).diff(x2) # смешанные =>побочная диагональ
coef4 = P.diff(x2).diff(x1) # смешанные =>побочная диагональ


In [467]:
delta1 = coef1 # 1-ый минор
delta2 = coef1*coef2 - coef3*coef4 # 2-ой минор
delta1, delta2

(-10, 5)

In [499]:
R.subs({x1: p_1_val, x2: p_2_val})

474

In [475]:
m = np.array([
    [coef1, coef3],
    [coef4, coef2],
], dtype=float)
m

array([[-10.,  -5.],
       [ -5.,  -3.]])

In [474]:
np.linalg.det(m) # с этим не разобрался

5.000000000000001

<img src="img/t5.png" width="500"/>

In [489]:
p_1, p_2 = sp.symbols('p_1, p_2')

In [490]:
x_1 = 50 - p_1
x_2 = 80 - p_2 / 2
C = 4 * x_1 ** 2 + 5 * x_1 * x_2 + 6 * x_2 ** 2
C

4*(50 - p_1)**2 + 6*(80 - p_2/2)**2 + (80 - p_2/2)*(250 - 5*p_1)

In [22]:
R = p_1 * x_1 + p_2 * x_2
R

p_1*(50 - p_1) + p_2*(80 - p_2/2)

In [23]:
P = R - C
P

p_1*(50 - p_1) + p_2*(80 - p_2/2) - 4*(50 - p_1)**2 - 6*(80 - p_2/2)**2 - (80 - p_2/2)*(250 - 5*p_1)

In [24]:
P_diff_p_1 = P.diff(p_1)
P_diff_p_1

-10*p_1 - 5*p_2/2 + 850

In [25]:
P_diff_p_2 = P.diff(p_2)
P_diff_p_2

-5*p_1/2 - 4*p_2 + 685

In [26]:
res = sp.solve([sp.Eq(0, P_diff_p_1), sp.Eq(0, P_diff_p_2)])
p_1_val = res[p_1]
p_2_val = res[p_2]
print(f'p_1 = {p_1_val}, p_2 = {p_2_val}')

p_1 = 50, p_2 = 140


In [27]:
x_1_val = x_1.subs({p_1: p_1_val})
x_2_val = x_2.subs({p_2: p_2_val})
print(f'x_1 = {x_1_val}, x_2 = {x_2_val}')

x_1 = 0, x_2 = 10


In [28]:
R.subs({p_1: p_1_val, p_2: p_2_val})

1400

In [500]:
E_d_1 = x_1.diff() * p_1/ x_1
E_d_1 = sp.simplify(E_d_1)
E_d_1

p_1/(p_1 - 50)

In [501]:
E_d_2 = x_2.diff() * p_2 / x_2
E_d_2 = sp.simplify(E_d_2)
E_d_2

p_2/(p_2 - 160)

In [31]:
print(f'E_d_1({p_1_val}) = {E_d_1.subs({p_1: p_1_val})}')
print(f'E_d_2({p_2_val}) = {E_d_2.subs({p_2: p_2_val})}')

E_d_1(50) = zoo
E_d_2(140) = -7


In [32]:
m = np.array([
    [float(P.diff(p_1).diff(p_1)), float(P.diff(p_1).diff(p_2))],
    [float(P.diff(p_2).diff(p_1)), float(P.diff(p_2).diff(p_2))],
])
m

array([[-10. ,  -2.5],
       [ -2.5,  -4. ]])

In [33]:
np.linalg.det(m)

33.75

In [34]:
P

p_1*(50 - p_1) + p_2*(80 - p_2/2) - 4*(50 - p_1)**2 - 6*(80 - p_2/2)**2 - (80 - p_2/2)*(250 - 5*p_1)

In [502]:
# 15.02 - все просмотрено, лучше смотреть предыдущую задачу

<img src="img/01_equilibrium_point.png" width="500"/>

In [19]:
x = sp.Symbol('x')
p_D, p_S = sp.symbols('p_D p_S')
p_D = sp.solve(sp.Eq(4 * p_D + x, 34), p_D)[0]
p_S = sp.solve(sp.Eq(6 * p_S - x, 38), p_S)[0]

In [20]:
p_D


17/2 - x/4

In [21]:
p_S

x/6 + 19/3

In [22]:
# 1) найти точку рыночного равновесия
p_eq = sp.solve(sp.Eq(p_D, p_S), x)[0]  # точка рыночного равновесия
p_eq


26/5

In [23]:
# 2) найти точку рыночного равновесия с учетом налога с продавцов 20%. Доход государства от налога
(t := p_S*0.2)  # налог 20% от стоимости ед. продукции

0.0333333333333333*x + 1.26666666666667

In [24]:
(new_p_eq := sp.solve(sp.Eq(p_D, p_S + t), x)[0])  # новая точка рыночного равновесия с учетом налога

2.00000000000000

In [25]:
(S_p := new_p_eq * t.subs({x: new_p_eq}))  # доход государства

2.66666666666667

In [516]:
# 3) правительство покупает излишки продукции, установив цену = 7.5
x_D, x_S = sp.symbols('x_D x_S')
p_val = 7.5
x_D_val = sp.solve(sp.Eq(4 * p_val + x_D, 34), x_D)[0]
x_S_val = sp.solve(sp.Eq(6 * p_val - x_S, 38), x_S)[0]
x_D_val, x_S_val  # могут купить, предлагают
# x_D - спрос
# x_S - предложение

(4.00000000000000, 7.00000000000000)

In [517]:
(x_S_val - x_D_val) * p_val  # на эту сумму правительству придется выкупить

22.5000000000000

In [518]:
# следующая задача
# найти (x_1;x_2) - прибыль -> max
x_1, x_2 = sp.symbols('x_1 x_2')
p_1, p_2 = sp.symbols('p_1 p_2')
x_1 = sp.solve(sp.Eq(4 * p_1 + x_1, 34), x_1)[0]  # функция спроса на продукт 1
x_2 = sp.solve(sp.Eq(6 * p_2 + x_2, 38), x_2)[0]  # функция предложения на продукт 2
C = 4 * x_1 ** 2 + 5 * x_1 * x_2 + 6 * x_2 ** 2  # функция издержек фирмы

In [519]:
(R := p_1 * x_1 + p_2 * x_2)  # выручка

p_1*(34 - 4*p_1) + p_2*(38 - 6*p_2)

In [520]:
(P := R - C)  # прибыль

p_1*(34 - 4*p_1) + p_2*(38 - 6*p_2) - 4*(34 - 4*p_1)**2 - 6*(38 - 6*p_2)**2 - (38 - 6*p_2)*(170 - 20*p_1)

In [521]:
(P_diff_p_1 := P.diff(p_1))

-136*p_1 - 120*p_2 + 1882

In [522]:
(P_diff_p_2 := P.diff(p_2))

-120*p_1 - 444*p_2 + 3794

In [523]:
res = sp.solve([sp.Eq(0, P_diff_p_1), sp.Eq(0, P_diff_p_2)])
p_1_val = res[p_1]
p_2_val = res[p_2]
print(f'p_1 = {p_1_val.evalf(4)}, p_2 = {p_2_val.evalf(4)}')

p_1 = 8.271, p_2 = 6.310


In [524]:
x_1_val = x_1.subs({p_1: p_1_val})
x_2_val = x_2.subs({p_2: p_2_val})
print(f'x_1 = {x_1_val.evalf(4)}, x_2 = {x_2_val.evalf(4)}')

x_1 = 0.9165, x_2 = 0.1420


In [525]:
R.subs({p_1: p_1_val, p_2: p_2_val}).evalf(4)

8.476

In [526]:
# проверка: точка max
m = np.array([
    [float(P.diff(p_1).diff(p_1)), float(P.diff(p_1).diff(p_2))],
    [float(P.diff(p_2).diff(p_1)), float(P.diff(p_2).diff(p_2))],
])
m, (det := np.linalg.det(m))

(array([[-136., -120.],
        [-120., -444.]]),
 45983.99999999998)

In [527]:
print(f'Найденная точка - точка max? {m[0, 0] < 0 < det}')

Найденная точка - точка max? True


<img src="img/02_lec.png" width="500"/>
<br>
<img src="img/03_lec.png" width="500"/>
<br>
<img src="img/04_lec.png" width="500"/>
<br>
<img src="img/05_lec.png" width="500"/>
<br>
<img src="img/06_lec.png" width="500"/>
<br>
<img src="img/05_lec.png" width="500"/>

In [2]:
x_1, x_2 = sp.symbols('x_1 x_2')
p_1, p_2 = 10, 2
I = 60
eq_I = sp.Eq(x_1 * p_1 + x_2 * p_2, I)
U = x_1 ** (1 / 2) * x_2 ** (2 / 3)
eq_I

Eq(10*x_1 + 2*x_2, 60)

In [3]:
U

x_1**0.5*x_2**0.666666666666667

In [79]:
eq_U = sp.Eq(U.diff(x_1) / U.diff(x_2), p_1 / p_2)
eq_U

Eq(0.75*x_2**1.0/x_1**1.0, 5.0)

In [81]:
res = sp.solve((eq_I, eq_U))
x_1_val = res[x_1]
x_2_val = res[x_2]
x_1_val, x_2_val

(2.57142857142857, 17.1428571428571)

<img src="img/08_prac.png" width="500"/>

In [83]:
# 3) норма замены
MRS = (U.diff(x_1) / U.diff(x_2)).subs({x_1: x_1_val, x_2: x_2_val})
MRS

5.00000000000000

In [89]:
# 4) ф-ия спроса, эл. спроса
p_1, p_2 = sp.symbols('p_1 p_2')
eq_I = sp.Eq(p_1 * x_1 + p_2 * x_2, I)
eq_I

Eq(p_1*x_1 + p_2*x_2, 60)

In [91]:
eq_U = sp.Eq(U.diff(x_1) / U.diff(x_2), p_1 / p_2)
eq_U

Eq(0.75*x_2**1.0/x_1**1.0, p_1/p_2)

In [133]:
res = sp.solve((eq_I, eq_U))[0]
res

{p_1: 25.7142857142857/x_1, p_2: 34.2857142857143/x_2}

In [127]:
sp.solve(sp.Eq(res[p_1], p_1), p_1)

[25.7142857142857/x_1]

In [128]:
sp.solve(sp.Eq(res[p_2], p_2), x_2)

[34.2857142857143/p_2]

In [129]:
# ур-е спроса для x_1
x_1_val = 180 / (7 * p_1)
x_1_val

180/(7*p_1)

In [130]:
# эластичность
E_d = x_1_val.diff() * p_1 / x_1_val
E_d = sp.simplify(E_d)
E_d

-1

In [179]:
x_1, x_2 = sp.symbols('x_1 x_2')
p_1, p_2 = 6, 2
I = 60
eq_I = sp.Eq(x_1 * p_1 + x_2 * p_2, I)
U = (x_1 - 1) ** (1/4) * (x_2 - 3) ** (3/4)
eq_I

Eq(6*x_1 + 2*x_2, 60)

In [180]:
eq_U = sp.Eq(U.diff(x_1) / U.diff(x_2), p_1 / p_2)
eq_U

Eq(0.333333333333333*(x_2 - 3)**1.0/(x_1 - 1)**1.0, 3.0)

In [181]:
# 1) U(x1,x2) -> max
res = sp.solve((eq_I, eq_U))
x_1_val = res[x_1]
x_2_val = res[x_2]
x_1_val, x_2_val

(3.00000000000000, 21.0000000000000)

In [182]:
# 2) норма замены
MRS = (U.diff(x_1) / U.diff(x_2)).subs({x_1: x_1_val, x_2: x_2_val})
MRS

3.00000000000000

In [191]:
# 3) ф-ия спроса, эл. спроса
p_1, p_2 = sp.symbols('p_1 p_2')
eq_I = sp.Eq(p_1 * x_1 + p_2 * x_2, I)
eq_I

Eq(p_1*x_1 + p_2*x_2, 60)

In [192]:
eq_U = sp.Eq(U.diff(x_1) / U.diff(x_2), p_1 / p_2)
eq_U

Eq(0.333333333333333*(x_2 - 3)**1.0/(x_1 - 1)**1.0, p_1/p_2)

In [193]:
res = sp.solve((eq_I, eq_U), (x_1, x_2))
res

{x_1: 0.75*(p_1 - p_2 + 20.0)/p_1, x_2: 0.75*(-p_1 + p_2 + 60.0)/p_2}

In [194]:
x_1_val = res[x_1]
x_1_val

0.75*(p_1 - p_2 + 20.0)/p_1

In [195]:
x_2_val = res[x_2]
x_2_val

0.75*(-p_1 + p_2 + 60.0)/p_2

In [196]:
# эластичность
E_d = x_1_val.diff(p_1) * p_1 / x_1_val
E_d = sp.simplify(E_d)
E_d

(1.0*p_2 - 20.0)/(p_1 - p_2 + 20.0)

In [199]:
sp.simplify(x_1_val.diff(p_1))

(0.75*p_2 - 15.0)/p_1**2

<img src="img/09_prac.png" width="500"/>

In [201]:
x_1, x_2 = sp.symbols('x_1 x_2')
Q = 2 * x_1 ** (1/4) * x_2 ** (1/2)
p = 12
q_1, q_2 = 2, 6

In [202]:
C = q_1 * x_1 + q_2 * x_2
C

2*x_1 + 6*x_2

In [ ]:
P = p * Q - C

In [8]:
# №39 стр. 147
x_1, x_2 = sp.symbols('x_1 x_2')
p_1, p_2 = 16, 20
I = 20_000
eq_I = sp.Eq(x_1 * p_1 + x_2 * p_2, I)
U = x_1 ** 2 * x_2 ** 3
eq_I

Eq(16*x_1 + 20*x_2, 20000)

In [9]:
eq_U = sp.Eq(U.diff(x_1) / U.diff(x_2), p_1 / p_2)
eq_U

Eq(2*x_2/(3*x_1), 0.8)

In [10]:
# 1) U(x1,x2) -> max
res = sp.solve((eq_I, eq_U))
x_1_val = res[x_1]
x_2_val = res[x_2]
x_1_val, x_2_val

(500.000000000000, 600.000000000000)

In [9]:
# №18 стр. 161
x_1, x_2 = sp.symbols('x_1 x_2')
p = 32
w_1, w_2 = 4, 16
Q = 8 * x_1 ** (1 / 4) * x_2 ** (1 / 4)
C = w_1 * x_1 + w_2 * x_2

In [10]:
(P := p * Q - C)

256*x_1**0.25*x_2**0.25 - 4*x_1 - 16*x_2

In [11]:
(eq_1 := sp.Eq(P.diff(x_1), 0))

Eq(64.0*x_2**0.25/x_1**0.75 - 4, 0)

In [12]:
(eq_2 := sp.Eq(P.diff(x_2), 0))

Eq(64.0*x_1**0.25/x_2**0.75 - 16, 0)

In [13]:
(res := sp.solve((eq_1, eq_2))[0])

{x_1: 128.000000000000, x_2: 32.0000000000000}

In [14]:
# план рентабелен
P.subs(res)

1024.00000000000

<img src="img/10_practice.png" width="500"/>

In [247]:
x_1, x_2 = 89, 88
X = np.array([[3, 8],
              [5, 7]])
Y = np.array([[100 * 2],
              [100 * 1.5]])

In [248]:
(A := X / np.array([[100, 100], [100, 100]]).T)

array([[0.03, 0.08],
       [0.05, 0.07]])

In [249]:
# 1) > 0, матрица продуктивна
(S := np.linalg.inv(np.eye(2) - A))

array([[1.03551943, 0.08907694],
       [0.05567309, 1.0800579 ]])

In [250]:
(B := A * Y.T)

array([[ 6. , 12. ],
       [10. , 10.5]])

In [251]:
# 2)
Y.reshape(1, -1) - B.sum(axis=0).reshape(1, -1)

array([[184. , 127.5]])

In [252]:
# 3)
Y_ = np.array([[x_1],
               [x_2 * 1.1]])
S.dot(Y_)

array([[100.78387707],
       [109.50450952]])

<img src="img/11_practice.png" width="600"/>

In [259]:
x_1, x_2 = 100, 130
X = np.array([[11, 30],
              [17, 20]])

In [260]:
(A := X / np.array([[141, 141],
                    [167, 167]]).T)

array([[0.07801418, 0.17964072],
       [0.12056738, 0.11976048]])

In [261]:
# 1) > 0, матрица продуктивна
(S := np.linalg.inv(np.eye(2) - A))

array([[1.11435484, 0.22741935],
       [0.15263441, 1.1672043 ]])

In [262]:
Y = np.array([[141 * 2],
              [167]])
(B := A * Y.T)

array([[22., 30.],
       [34., 20.]])

In [263]:
# 2) конечное потребление
(Y.reshape(1, -1) - B.sum(axis=0).reshape(1, -1)).T

array([[226.],
       [117.]])

In [264]:
# 3) валовый выпуск
Y_ = np.array([[120],
               [x_2]])
S.dot(Y_)

array([[163.28709677],
       [170.05268817]])

In [309]:
A = sp.Matrix([[1, 2],
              [3, 4]])
k = sp.symbols('k')

In [317]:
(M := A - sp.diagonalize_vector(sp.Matrix([k, k])))

Matrix([
[1 - k,     2],
[    3, 4 - k]])