In [10]:
import numpy as np
import sympy as sp
from IPython.display import display, Math

Дана балансовая таблица в двухотраслевой модели Леонтьева.   
Постройте структурную матрицу (матрицу прямых затрат) и проверьте её продуктивность.   
Производители, Потребители(I,II), конечный продукт, ввп   
Производитель 1(row1):   3, 8, 89, 100   
Производитель 2(row1):   5, 7, 88, 100   
Вычислите конечное потребление каждой отрасли, если объем валового выпуска каждой отрасли увеличится соответственно на 100% И 50%;   
найдите в данном случае чистую продукцию отраслей. Найдите валовой выпуск,   
если конечное потребление первой отрасли не изменилось, а второй — увеличилось на 10%.   

In [11]:
x_1, x_2 = 89, 88 # конечный продукт
X = np.array([[3, 8],
              [5, 7]])
vvp_1 = 100
vvp_2 = 100              
Y = np.array([[vvp_1 * 2], # 2 - 100%, 1,5 - 50%
              [vvp_2 * 1.5]])
x_10_perc = 1.1

In [12]:
A = X / np.array([[vvp_1, vvp_1],
                    [vvp_2, vvp_2]]).T
A                

array([[0.03, 0.08],
       [0.05, 0.07]])

In [13]:
E_A = np.eye(2)-A
E_A

array([[ 0.97, -0.08],
       [-0.05,  0.93]])

In [14]:
# 1) > 0, матрица продуктивна
# A^-1
E_A_inv = np.linalg.inv(E_A)
E_A_inv

array([[1.03551943, 0.08907694],
       [0.05567309, 1.0800579 ]])

In [15]:
B = A * Y.T
B

array([[ 6. , 12. ],
       [10. , 10.5]])

In [16]:
# 2)
t2 = (Y.T - B.sum(axis=0))[0]
t2

array([184. , 127.5])

In [17]:
# 3)
Y_ = np.array([x_1, x_2 * x_10_perc])  # увеличилось на 10
t3 = E_A_inv.dot(Y_)
t3


array([100.78387707, 109.50450952])

## Отчет

In [18]:
print("A =\n", A)
print("\nE - A =\n",E_A)
print("ответ на вопрос пункта 1:")
display(Math(r"(E-A)^{-1} ="))
print(E_A_inv)
print("------------------------------------")
print("Y =", Y.T)
print("B =\n",B)
print("ответ на вопрос пункта 2:")
print(f"I = {Y.T[0][0]} - {B[0][0]} - {B[1][0]} = {t2[0]}")
print(f"II = {Y.T[0][1]} - {B[0][1]} - {B[1][1]} = {t2[1]}")
print("------------------------------------")
print("ответ на вопрос пункта 3:")
print("Y =",E_A_inv,"*",Y_, "=", t3)

A =
 [[0.03 0.08]
 [0.05 0.07]]

E - A =
 [[ 0.97 -0.08]
 [-0.05  0.93]]
ответ на вопрос пункта 1:


<IPython.core.display.Math object>

[[1.03551943 0.08907694]
 [0.05567309 1.0800579 ]]
------------------------------------
Y = [[200. 150.]]
B =
 [[ 6.  12. ]
 [10.  10.5]]
ответ на вопрос пункта 2:
I = 200.0 - 6.0 - 10.0 = 184.0
II = 150.0 - 12.0 - 10.500000000000002 = 127.5
------------------------------------
ответ на вопрос пункта 3:
Y = [[1.03551943 0.08907694]
 [0.05567309 1.0800579 ]] * [89.  96.8] = [100.78387707 109.50450952]
