In [73]:
import numpy as np
import sympy as sp
from IPython.display import display, Math

# Variables

In [74]:
x_1, x_2 = 100, 130  # конечный продукт
X = np.array([[11, 30],  # матрица потребителей
              [17, 20]])
# Валовый продукт:
vvp_1 = 141
vvp_2 = 167

# Как изменяется объем валового выпуска
coef_vvp_1 = 2  # 1 - by defalut(не изменится)
coef_vvp_2 = 1  # 1 - by defalut(не изменится)
Y = np.array([[vvp_1 * coef_vvp_1],
              [vvp_2 * coef_vvp_2]]).T

# конечное потребление первой/второй отрасли увеличилось 'в' %
consumption_coef_1 = 0   # 0 - by defalut(не изменится)
consumption_coef_2 = 0     # 0 - by defalut(не изменится)

# конечное потребление первой/второй отрасли увеличилось 'на'
consumption_units_1 = 20  # 0 - by defalut(не изменится)
consumption_units_2 = 0  # 0 - by defalut(не изменится)

# если написано увеличлось 'до', тогда считаем разницу в ручную и дописываем коэфф в consumption_units
# TODO может быть доделать с условием ДО
 
Y_ = np.array([x_1 * (1+consumption_coef_1/100) + consumption_units_1,
               x_2 * (1+consumption_coef_2/100) + consumption_units_2])


# Task

Дана балансовая таблица в двухотраслевой модели Леонтьева.   
Постройте структурную матрицу (матрицу прямых затрат) и проверьте её продуктивность.   
| **Производители** | **Потребители I** | **Потребители II** | **Конечный продукт** | **Валовый продукт** |
|-------------------|-------------------|--------------------|----------------------|---------------------|
| I                 | 13                | 38                 | 100                  | 151                 |
| II                | 24                | 30                 | 160                  | 214                 |

Вычислите конечное потребление каждой отрасли, если объем валового выпуска первой отрасли не изменится, а второй увеличится вдвое   
найдите в данном случае чистую продукцию отраслей. Найдите валовой выпуск, если конечное потребление первой отрасли увеличилось на 12%,   
а второй — не изменилось   

# Solution

In [75]:
A = X / np.array([[vvp_1, vvp_1],
                    [vvp_2, vvp_2]]).T
A

array([[0.07801418, 0.17964072],
       [0.12056738, 0.11976048]])

In [76]:
E_A = np.eye(2)-A
E_A

array([[ 0.92198582, -0.17964072],
       [-0.12056738,  0.88023952]])

In [77]:
# 1) > 0, матрица продуктивна
# A^-1
E_A_inv = np.linalg.inv(E_A)
E_A_inv

array([[1.11435484, 0.22741935],
       [0.15263441, 1.1672043 ]])

In [78]:
B = A * Y
B

array([[22., 30.],
       [34., 20.]])

In [79]:
# 2)
t2 = (Y - B.sum(axis=0))[0]
t2

array([226., 117.])

In [80]:
# 3)
t3 = E_A_inv.dot(Y_)
t3


array([163.28709677, 170.05268817])

# Отчет

In [81]:
display(Math(rf"A = {sp.latex(sp.Matrix(np.round(A, 4)))}"))
display(Math(rf"E - A = {sp.latex(sp.Matrix(np.round(E_A, 4)))}"))
print("ответ на вопрос пункта 1:")
display(Math(rf"(E-A)^{-1} = {sp.latex(sp.Matrix(np.round(E_A_inv, 4)))}"))
print("------------------------------------")
display(Math(rf"X = {sp.latex(sp.Matrix(Y.T))}"))
display(Math(rf"B = {sp.latex(sp.Matrix(B))}"))
print("ответ на вопрос пункта 2:")
print(f"I = {Y[0][0]} - {round(B[0][0], 2)} - {round(B[1][0], 2)} = {t2[0]}")
print(f"II = {Y[0][1]} - {round(B[0][1], 2)} - {round(B[1][1], 2)} = {t2[1]}")
print("------------------------------------")
print("ответ на вопрос пункта 3:")
display(Math(rf" \bar{{X}}^{{\star}} = (E-A)^{-1} *  \bar{{y}}^{{\star}}= {sp.latex(sp.Matrix(np.round(t3, 4)))}"))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

ответ на вопрос пункта 1:


<IPython.core.display.Math object>

------------------------------------


<IPython.core.display.Math object>

<IPython.core.display.Math object>

ответ на вопрос пункта 2:
I = 282 - 22.0 - 34.0 = 226.0
II = 167 - 30.0 - 20.0 = 117.0
------------------------------------
ответ на вопрос пункта 3:


<IPython.core.display.Math object>