In [1]:
import numpy as np
import sympy as sp
from IPython.display import display, Math

Дана балансовая таблица в двухотраслевой модели Леонтьева.   
Постройте структурную матрицу (матрицу прямых затрат) и проверьте её продуктивность.   
Производители, Потребители(I,II), конечный продукт, ввп   
Производитель 1(row1):   11, 30, 100, 141   
Производитель 2(row1):   17, 20, 130, 167   
Вычислите конечное потребление каждой отрасли, если объем валового выпуска первой отрасли увеличится вдвое, а второй не изменится   
найдите в данном случае чистую продукцию отраслей. Найдите валовой выпуск,   
если конечное потребление первой отрасли увеличилось до 120, а второй не изменилось.   

In [2]:
x_1, x_2 = 100, 130
X = np.array([[11, 30],
              [17, 20]])
vvp_1 = 141
vvp_2 = 167              
Y = np.array([[vvp_1 * 2], # вдвое
              [vvp_2]])
x_120 = 120

In [3]:
A = X / np.array([[vvp_1, vvp_1],
                    [vvp_2, vvp_2]]).T
A                    

array([[0.07801418, 0.17964072],
       [0.12056738, 0.11976048]])

In [4]:
E_A = np.eye(2)-A
E_A

array([[ 0.92198582, -0.17964072],
       [-0.12056738,  0.88023952]])

In [5]:
# 1) > 0, матрица продуктивна
# A^-1
E_A_inv = np.linalg.inv(E_A)
E_A_inv

array([[1.11435484, 0.22741935],
       [0.15263441, 1.1672043 ]])

In [6]:
B = A * Y.T
B

array([[22., 30.],
       [34., 20.]])

In [7]:
# 2)
t2 = (Y.T - B.sum(axis=0))[0]
t2

array([226., 117.])

In [8]:
# 3)
Y_ = np.array([x_120, x_2])  # первой стало 120(условие задачи)
t3 = E_A_inv.dot(Y_)
t3


array([163.28709677, 170.05268817])

## Отчет

In [9]:
print("A =\n", A)
print("\nE - A =\n",E_A)
print("ответ на вопрос пункта 1:")
display(Math(r"(E-A)^{-1} ="))
print(E_A_inv)
print("------------------------------------")
print("Y =", Y.T)
print("B =\n",B)
print("ответ на вопрос пункта 2:")
print(f"I = {Y.T[0][0]} - {B[0][0]} - {B[1][0]} = {t2[0]}")
print(f"II = {Y.T[0][1]} - {B[0][1]} - {B[1][1]} = {t2[1]}")
print("------------------------------------")
print("ответ на вопрос пункта 3:")
print("Y =",E_A_inv,"*",Y_, "=", t3)

A =
 [[0.07801418 0.17964072]
 [0.12056738 0.11976048]]

E - A =
 [[ 0.92198582 -0.17964072]
 [-0.12056738  0.88023952]]
ответ на вопрос пункта 1:


<IPython.core.display.Math object>

[[1.11435484 0.22741935]
 [0.15263441 1.1672043 ]]
------------------------------------
Y = [[282 167]]
B =
 [[22. 30.]
 [34. 20.]]
ответ на вопрос пункта 2:
I = 282 - 22.0 - 34.0 = 226.0
II = 167 - 30.0 - 20.0 = 117.0
------------------------------------
ответ на вопрос пункта 3:
Y = [[1.11435484 0.22741935]
 [0.15263441 1.1672043 ]] * [120 130] = [163.28709677 170.05268817]
